package com.acetaxi.registration.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.stereotype.Component;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@Component
@Data
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Driver")
public class Driver {
//    @DynamoDBHashKey(attributeName = "id")
//    @DynamoDBAutoGeneratedKey
//    private String id; // DynamoDB requires a String hash key

	@DynamoDBHashKey(attributeName = "email")
	private String email;

	@DynamoDBAttribute(attributeName = "firstName")
	private String firstName;

	@DynamoDBAttribute(attributeName = "lastName")
	private String lastName;

	@DynamoDBAttribute(attributeName = "mobileNumber")
	private String mobileNumber;

	@DynamoDBAttribute(attributeName = "dob")
	private String dob; // Date should be stored as a String

	@DynamoDBAttribute(attributeName = "status")
	private String status;
	@DynamoDBAttribute(attributeName = "gender")
	private String gender;
	@DynamoDBAttribute(attributeName = "drivingLicenseNumber")
	private String drivingLicenseNumber;
	@DynamoDBAttribute(attributeName = "licenseExpiry")
	private String licenseExpiry;
	@DynamoDBAttribute(attributeName = "passportNumber")
	private String passportNumber;
	@DynamoDBAttribute(attributeName = "ssnumber")
	private String ssnumber;
	@DynamoDBAttribute(attributeName = "areYouWorking")
	private String areYouWorking;
	@DynamoDBAttribute(attributeName = "stateOrRegion")
	private String stateOrRegion;
	@DynamoDBAttribute(attributeName = "postalCode")
	private String postalCode;
	@DynamoDBAttribute(attributeName = "address")
	private String address;
	@DynamoDBAttribute(attributeName = "resident")
	private String resident;
	@DynamoDBAttribute(attributeName = "ownTaxiBoard")
	private boolean ownTaxiBoard;

}
