package com.acetaxi.registration.entity;

import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Data
@Component
@DynamoDBTable(tableName = "User")
public class User {

//    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
//	private String id;

	@DynamoDBHashKey(attributeName = "email")
	private String email;

	@DynamoDBAttribute
	private String firstName;
	@DynamoDBAttribute
	private String lastName;
	@DynamoDBAttribute
	private String mobileNumber;

	@DynamoDBAttribute
	private String password;
//	@DynamoDBAttribute
//	private String repassword;

}
